[package]
name = "rust-file-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.0"
gio = "0.9.0"
dirs = "3.0"
pango = "0.9"
